version: "3.3"

services:
  pythondb:
    build: ./
    container_name: pythondb
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
  
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example